<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\app_intro.mp4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\app_intro.mp4">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\icon_tools_circle_white.png" />
    <Resource Include="Resources\icon_tools_eraser_white.png" />
    <Resource Include="Resources\icon_tools_highlighter_white.png" />
    <Resource Include="Resources\icon_tools_line_white.png" />
    <Resource Include="Resources\icon_tools_pencil_white.png" />
    <Resource Include="Resources\icon_tools_rect_white.png" />
    <Resource Include="Resources\icon_tools_shape_white.png" />
    <Resource Include="Resources\icon_tools_thickness_white.png" />
    <Resource Include="Resources\icon_tools_triangle_white.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="RBush" Version="4.0.0" />
    <PackageReference Include="ScreenRecorderLib" Version="6.5.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.0" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.0" />
    <PackageReference Include="WPF-UI" Version="4.0.2" />
    <PackageReference Include="WPF-UI.Tray" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\HelpMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HelpMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\HelpMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>HelpMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
