//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeNote.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpMessages() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeNote.Resources.HelpMessages", typeof(HelpMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   앱을 완전히 종료하려면 Ctrl + Q 키를 누르거나, 윈도우 우측 아래 숨겨진 아이콘 표시를 클릭하여 DeNote 아이콘 우클릭 후 종료를 눌러주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   앱 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExitApp_Title {
            get {
                return ResourceManager.GetString("ExitApp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문의사항은 고객센터를 이용해주세요.
        ///https://www.denote.co.kr/help/과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpCenterLink {
            get {
                return ResourceManager.GetString("HelpCenterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문의사항과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HelpCenterLink_Title {
            get {
                return ResourceManager.GetString("HelpCenterLink_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   화면을 길게 누르거나 마우스 오른쪽 버튼을 클릭하면 드로잉툴 선택창이 나타납니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectDrawingTool {
            get {
                return ResourceManager.GetString("SelectDrawingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도구 선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectDrawingTool_Title {
            get {
                return ResourceManager.GetString("SelectDrawingTool_Title", resourceCulture);
            }
        }
    }
}
